In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
import functools

<h2>Load the Data</h2>

In [3]:
fat_supply_csv = "../Resources/Fat_Supply_Quantity_Data.csv"
fat_supply_df = pd.read_csv(fat_supply_csv)
fat_supply_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetal Products,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population
0,Afghanistan,0.0,21.64,6.22,0.0,8.04,0.69,0.03,0.42,6.12,...,28.37,17.08,0.36,4.5,29.8,0.14,0.01,0.12,0.01,38928000
1,Albania,0.0,32.00,3.42,0.0,2.67,1.64,0.14,0.64,8.74,...,18.00,9.24,0.65,22.3,6.2,2.97,0.05,1.79,1.12,2838000
2,Algeria,0.0,14.42,0.90,0.0,4.20,1.22,0.20,0.58,3.90,...,35.59,27.36,0.51,26.6,3.9,0.24,0.01,0.17,0.07,44357000
3,Angola,0.0,15.30,1.31,0.0,6.55,0.15,1.42,0.35,11.03,...,34.70,22.46,0.12,6.8,25.0,0.06,0.00,0.06,0.00,32522000
4,Antigua and Barbuda,0.0,27.70,4.67,0.0,3.22,0.39,1.53,1.22,14.32,...,22.30,14.44,0.25,19.1,0.0,0.29,0.01,0.19,0.10,98000

In [4]:
kcal_supply_csv = "../Resources/Food_Supply_kcal_Data.csv"
kcal_supply_df = pd.read_csv(kcal_supply_csv)
kcal_supply_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetal Products,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population
0,Afghanistan,0.00,4.78,0.85,0.0,37.12,0.15,0.00,1.48,1.20,...,45.25,2.30,0.75,4.5,29.8,0.14,0.01,0.12,0.01,38928000
1,Albania,0.91,16.09,1.06,0.0,16.21,0.81,0.15,3.90,3.87,...,33.91,2.82,2.75,22.3,6.2,2.97,0.05,1.79,1.12,2838000
2,Algeria,0.09,6.03,0.19,0.0,25.01,0.42,0.12,3.18,1.25,...,43.97,5.76,2.05,26.6,3.9,0.24,0.01,0.17,0.07,44357000
3,Angola,1.94,4.69,0.26,0.0,18.35,0.04,0.84,2.31,2.93,...,45.32,4.27,0.35,6.8,25.0,0.06,0.00,0.06,0.00,32522000
4,Antigua and Barbuda,2.30,15.37,1.54,0.0,13.72,0.21,1.73,3.68,7.04,...,34.62,4.69,1.30,19.1,0.0,0.29,0.01,0.19,0.10,98000

In [5]:
food_quantity_csv = "../Resources/Food_Supply_Quantity_kg_Data.csv"
food_quantity_df = pd.read_csv(food_quantity_csv)
food_quantity_df.head()

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population
0,Afghanistan,0.00,0.20,9.43,0.0,24.81,0.21,0.04,5.35,1.20,...,0.53,6.76,40.56,4.5,29.8,0.14,0.01,0.12,0.01,38928000
1,Albania,1.67,0.14,18.77,0.0,5.78,0.58,0.21,6.79,1.88,...,0.33,11.78,31.23,22.3,6.2,2.97,0.05,1.79,1.12,2838000
2,Algeria,0.27,0.03,9.63,0.0,13.68,0.53,0.24,6.38,1.13,...,1.03,11.65,40.37,26.6,3.9,0.24,0.01,0.17,0.07,44357000
3,Angola,5.81,0.06,4.93,0.0,9.11,0.06,1.77,6.00,2.06,...,0.65,2.30,45.07,6.8,25.0,0.06,0.00,0.06,0.00,32522000
4,Antigua and Barbuda,3.58,0.01,16.66,0.0,6.00,0.23,4.15,10.75,5.69,...,0.81,5.45,33.32,19.1,0.0,0.29,0.01,0.19,0.10,98000

In [6]:
protein_supply_csv = "../Resources/Protein_Supply_Quantity_Data.csv"
protein_supply_df = pd.read_csv(protein_supply_csv)
protein_supply_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Miscellaneous,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population
0,Afghanistan,0.00,9.75,0.03,0.0,35.98,0.41,0.06,0.58,3.13,...,0.00,1.14,0.05,4.5,29.8,0.14,0.01,0.12,0.01,38928000
1,Albania,0.18,27.75,0.07,0.0,14.23,1.81,0.63,1.28,7.66,...,0.01,3.25,0.05,22.3,6.2,2.97,0.05,1.79,1.12,2838000
2,Algeria,0.03,13.84,0.01,0.0,26.56,1.29,0.64,1.16,3.51,...,0.03,3.13,0.14,26.6,3.9,0.24,0.01,0.17,0.07,44357000
3,Angola,0.63,15.23,0.03,0.0,20.39,0.18,5.44,1.28,7.62,...,0.01,0.81,0.09,6.8,25.0,0.06,0.00,0.06,0.00,32522000
4,Antigua and Barbuda,0.15,33.19,0.13,0.0,10.51,0.49,8.21,1.26,16.07,...,0.04,1.60,0.29,19.1,0.0,0.29,0.01,0.19,0.10,98000

<h2>Transform Dataframes</h2>

<h3>Fat Supply</h3>

In [7]:
## FAT SUPPY ##

# Create a filtered dataframe from specific columns
fat_supply_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
fat_supply_transformed= fat_supply_df[fat_supply_cols].copy()

# Rename the column headers
fat_supply_transformed = fat_supply_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_fat',
                                                    'Cereals - Excluding Beer':'cereals_fat',
                                                    'Eggs':'eggs_fat',
                                                    'Fruits - Excluding Wine': 'fruits_fat',
                                                    'Meat':'meat_fat',
                                                    'Milk - Excluding Butter':'milk_fat',
                                                    'Fish, Seafood': 'fish_seafood_fat', 
                                                    'Vegetables':'vegetables_fat',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
fat_supply_transformed.drop_duplicates("country", inplace=True)
fat_supply_transformed.set_index("country", inplace=True)

fat_supply_transformed

,animal_products_fat,cereals_fat,eggs_fat,fruits_fat,meat_fat,milk_fat,fish_seafood_fat,vegetables_fat,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,21.64,8.04,0.69,0.42,6.12,8.28,0.03,0.36,4.5,29.8,0.14,0.01,0.12,38928000
Albania,32.00,2.67,1.64,0.64,8.74,17.76,0.14,0.65,22.3,6.2,2.97,0.05,1.79,2838000
Algeria,14.42,4.20,1.22,0.58,3.90,8.09,0.20,0.51,26.6,3.9,0.24,0.01,0.17,44357000
Angola,15.30,6.55,0.15,0.35,11.03,1.23,1.42,0.12,6.8,25.0,0.06,0.00,0.06,32522000
Antigua and Barbuda,27.70,3.22,0.39,1.22,14.32,6.66,1.53,0.25,19.1,0.0,0.29,0.01,0.19,98000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),16.33,2.54,0.66,0.96,7.09,5.52,0.57,0.19,25.2,21.2,0.45,0.00,0.42,28645000
Vietnam,33.25,3.72,0.78,0.41,26.43,0.75,1.12,0.64,2.1,9.3,0.00,0.00,0.00,96209000
Yemen,12.54,11.53,0.55,0.26,8.00,1.35,0.38,0.17,14.1,38.9,0.01,0.00,0.00,29826000
Zambia,9.60,14.32,0.63,0.13,4.90,1.28,1.01,0.16,6.5,46.7,0.33,0.00,0.29,18384000
Zimbabwe,10.38,9.79,0.37,0.06,4.57,2.10,0.25,0.08,12.3,51.3,0.23,0.01,0.19,14863000

<h3>Food Quantity (kg)</h3>

In [8]:
## FOOD QUANTITY ##

# Create a filtered dataframe from specific columns
food_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
food_transformed= food_quantity_df[food_cols].copy()

# Rename the column headers
food_transformed = food_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_quantity',
                                                    'Cereals - Excluding Beer':'cereals_quantity',
                                                    'Eggs':'eggs_quantity',
                                                    'Fruits - Excluding Wine': 'fruits_quantity',
                                                    'Meat':'meat_quantity',
                                                    'Milk - Excluding Butter':'milk_quantity',
                                                    'Fish, Seafood': 'fish_seafood_quantity', 
                                                    'Vegetables':'vegetables_quantity',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
food_transformed.drop_duplicates("country", inplace=True)
food_transformed.set_index("country", inplace=True)


food_transformed

,animal_products_quantity,cereals_quantity,eggs_quantity,fruits_quantity,meat_quantity,milk_quantity,fish_seafood_quantity,vegetables_quantity,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,9.43,24.81,0.21,5.35,1.20,7.58,0.04,6.76,4.5,29.8,0.14,0.01,0.12,38928000
Albania,18.77,5.78,0.58,6.79,1.88,15.72,0.21,11.78,22.3,6.2,2.97,0.05,1.79,2838000
Algeria,9.63,13.68,0.53,6.38,1.13,7.62,0.24,11.65,26.6,3.9,0.24,0.01,0.17,44357000
Angola,4.93,9.11,0.06,6.00,2.06,0.83,1.77,2.30,6.8,25.0,0.06,0.00,0.06,32522000
Antigua and Barbuda,16.66,6.00,0.23,10.75,5.69,6.37,4.15,5.45,19.1,0.0,0.29,0.01,0.19,98000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),14.76,12.93,0.34,7.65,3.83,9.39,0.95,4.15,25.2,21.2,0.45,0.00,0.42,28645000
Vietnam,8.58,16.87,0.31,5.90,4.44,0.61,2.64,11.95,2.1,9.3,0.00,0.00,0.00,96209000
Yemen,5.79,27.21,0.26,5.13,2.79,1.89,0.52,3.21,14.1,38.9,0.01,0.00,0.00,29826000
Zambia,6.02,21.19,0.34,1.02,1.84,1.76,1.69,3.46,6.5,46.7,0.33,0.00,0.29,18384000
Zimbabwe,8.15,22.62,0.27,2.20,2.61,4.43,0.55,2.32,12.3,51.3,0.23,0.01,0.19,14863000

<h3>KCal Supply</h3>

In [9]:
## KCAL SUPPY ##

# Create a filtered dataframe from specific columns
kcal_supply_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
kcal_supply_transformed= kcal_supply_df[kcal_supply_cols].copy()

# Rename the column headers
kcal_supply_transformed = kcal_supply_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_kcal',
                                                    'Cereals - Excluding Beer':'cereals_kcal',
                                                    'Eggs':'eggs_kcal',
                                                    'Fruits - Excluding Wine': 'fruits_kcal',
                                                    'Meat':'meat_kcal',
                                                    'Milk - Excluding Butter':'milk_kcal',
                                                    'Fish, Seafood': 'fish_seafood_kcal', 
                                                    'Vegetables':'vegetables_kcal',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
kcal_supply_transformed.drop_duplicates("country", inplace=True)
kcal_supply_transformed.set_index("country", inplace=True)


kcal_supply_transformed

,animal_products_kcal,cereals_kcal,eggs_kcal,fruits_kcal,meat_kcal,milk_kcal,fish_seafood_kcal,vegetables_kcal,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,4.78,37.12,0.15,1.48,1.20,2.45,0.00,0.75,4.5,29.8,0.14,0.01,0.12,38928000
Albania,16.09,16.21,0.81,3.90,3.87,9.94,0.15,2.75,22.3,6.2,2.97,0.05,1.79,2838000
Algeria,6.03,25.01,0.42,3.18,1.25,3.99,0.12,2.05,26.6,3.9,0.24,0.01,0.17,44357000
Angola,4.69,18.35,0.04,2.31,2.93,0.51,0.84,0.35,6.8,25.0,0.06,0.00,0.06,32522000
Antigua and Barbuda,15.37,13.72,0.21,3.68,7.04,4.69,1.73,1.30,19.1,0.0,0.29,0.01,0.19,98000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),7.23,21.31,0.29,2.38,3.14,2.65,0.44,0.67,25.2,21.2,0.45,0.00,0.42,28645000
Vietnam,10.98,26.98,0.29,1.80,7.83,0.56,1.04,1.96,2.1,9.3,0.00,0.00,0.00,96209000
Yemen,3.47,32.07,0.15,1.19,2.01,0.65,0.17,0.36,14.1,38.9,0.01,0.00,0.00,29826000
Zambia,3.30,31.55,0.20,0.22,1.52,0.52,0.57,0.45,6.5,46.7,0.33,0.00,0.29,18384000
Zimbabwe,3.94,29.80,0.14,0.44,1.75,1.08,0.16,0.25,12.3,51.3,0.23,0.01,0.19,14863000

<h3>Protein Supply</h3>

In [10]:
## PROTEIN SUPPLY ##

# Create a filtered dataframe from specific columns
protein_supply_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
protein_supply_transformed= protein_supply_df[protein_supply_cols].copy()

# Rename the column headers
protein_supply_transformed = protein_supply_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_protein',
                                                    'Cereals - Excluding Beer':'cereals_protein',
                                                    'Eggs':'eggs_protein',
                                                    'Fruits - Excluding Wine': 'fruits_protein',
                                                    'Meat':'meat_protein',
                                                    'Milk - Excluding Butter':'milk_protein',
                                                    'Fish, Seafood': 'fish_seafood_protein', 
                                                    'Vegetables':'vegetables_protein',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
protein_supply_transformed.drop_duplicates("country", inplace=True)
protein_supply_transformed.set_index("country", inplace=True)

protein_supply_transformed

,animal_products_protein,cereals_protein,eggs_protein,fruits_protein,meat_protein,milk_protein,fish_seafood_protein,vegetables_protein,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,9.75,35.98,0.41,0.58,3.13,5.53,0.06,1.14,4.5,29.8,0.14,0.01,0.12,38928000
Albania,27.75,14.23,1.81,1.28,7.66,16.48,0.63,3.25,22.3,6.2,2.97,0.05,1.79,2838000
Algeria,13.84,26.56,1.29,1.16,3.51,8.06,0.64,3.13,26.6,3.9,0.24,0.01,0.17,44357000
Angola,15.23,20.39,0.18,1.28,7.62,1.15,5.44,0.81,6.8,25.0,0.06,0.00,0.06,32522000
Antigua and Barbuda,33.19,10.51,0.49,1.26,16.07,7.43,8.21,1.60,19.1,0.0,0.29,0.01,0.19,98000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),22.54,21.65,0.87,1.07,11.83,6.31,2.65,1.01,25.2,21.2,0.45,0.00,0.42,28645000
Vietnam,20.45,18.52,0.77,0.72,11.04,1.09,5.74,3.72,2.1,9.3,0.00,0.00,0.00,96209000
Yemen,10.01,35.12,0.43,0.49,5.95,1.96,0.94,0.54,14.1,38.9,0.01,0.00,0.00,29826000
Zambia,9.89,28.52,0.58,0.09,4.32,1.03,3.01,0.80,6.5,46.7,0.33,0.00,0.29,18384000
Zimbabwe,11.34,33.19,0.51,0.26,6.66,2.41,1.08,0.60,12.3,51.3,0.23,0.01,0.19,14863000

<h3>Merge dataframes into one</h3>

In [11]:
dfs = [food_transformed, kcal_supply_transformed, fat_supply_transformed, protein_supply_transformed]
nan_value = 0

##BECAUSE EACH DATASET HAS THE SAME DATA IN OBESITY, UNDERNOURISHED, CONFIRMED_CASES, DEATHS, RECOVERED, AND POPULATION THEY
##CAN BE MERGED INTO ONE LARGE DATAFRAME

covid_diet = functools.reduce(lambda left, right: pd.merge(left,right,on=['country', 'obesity', 'undernourished', 'confirmed_cases', 'deaths', 'recovered', 'population']), dfs)
covid_diet

,animal_products_quantity,cereals_quantity,eggs_quantity,fruits_quantity,meat_quantity,milk_quantity,fish_seafood_quantity,vegetables_quantity,obesity,undernourished,...,fish_seafood_fat,vegetables_fat,animal_products_protein,cereals_protein,eggs_protein,fruits_protein,meat_protein,milk_protein,fish_seafood_protein,vegetables_protein
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,9.43,24.81,0.21,5.35,1.20,7.58,0.04,6.76,4.5,29.8,...,0.03,0.36,9.75,35.98,0.41,0.58,3.13,5.53,0.06,1.14
Albania,18.77,5.78,0.58,6.79,1.88,15.72,0.21,11.78,22.3,6.2,...,0.14,0.65,27.75,14.23,1.81,1.28,7.66,16.48,0.63,3.25
Algeria,9.63,13.68,0.53,6.38,1.13,7.62,0.24,11.65,26.6,3.9,...,0.20,0.51,13.84,26.56,1.29,1.16,3.51,8.06,0.64,3.13
Angola,4.93,9.11,0.06,6.00,2.06,0.83,1.77,2.30,6.8,25.0,...,1.42,0.12,15.23,20.39,0.18,1.28,7.62,1.15,5.44,0.81
Antigua and Barbuda,16.66,6.00,0.23,10.75,5.69,6.37,4.15,5.45,19.1,0.0,...,1.53,0.25,33.19,10.51,0.49,1.26,16.07,7.43,8.21,1.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),14.76,12.93,0.34,7.65,3.83,9.39,0.95,4.15,25.2,21.2,...,0.57,0.19,22.54,21.65,0.87,1.07,11.83,6.31,2.65,1.01
Vietnam,8.58,16.87,0.31,5.90,4.44,0.61,2.64,11.95,2.1,9.3,...,1.12,0.64,20.45,18.52,0.77,0.72,11.04,1.09,5.74,3.72
Yemen,5.79,27.21,0.26,5.13,2.79,1.89,0.52,3.21,14.1,38.9,...,0.38,0.17,10.01,35.12,0.43,0.49,5.95,1.96,0.94,0.54
Zambia,6.02,21.19,0.34,1.02,1.84,1.76,1.69,3.46,6.5,46.7,...,1.01,0.16,9.89,28.52,0.58,0.09,4.32,1.03,3.01,0.80
Zimbabwe,8.15,22.62,0.27,2.20,2.61,4.43,0.55,2.32,12.3,51.3,...,0.25,0.08,11.34,33.19,0.51,0.26,6.66,2.41,1.08,0.60

<h2>Create Connection to Database</h2>

In [12]:
covid_diet.to_csv(r'C:\Users\Annika\dataframe.csv')

In [16]:
connection_string = "postgres:ilikecats@localhost:5432/food_db"
engine = create_engine(f'postgresql://{connection_string}')

In [17]:
engine.table_names()

C:\Users\Annika\anaconda2\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  """Entry point for launching an IPython kernel.

['covid_diet', 'fat_supply', 'kcal_supply', 'food_quantity', 'protein_supply']

<h2>Load Dataframe into SQL</h2>

In [18]:
covid_diet.to_sql(name='covid_diet', con=engine, if_exists='append', index=True)

In [19]:
fat_supply_transformed.to_sql(name='fat_supply', con=engine, if_exists='append', index=True)

In [20]:
food_transformed.to_sql(name='food_quantity', con=engine, if_exists='append', index=True)

In [21]:
kcal_supply_transformed.to_sql(name='kcal_supply', con=engine, if_exists='append', index=True)

In [22]:
protein_supply_transformed.to_sql(name='protein_supply', con=engine, if_exists='append', index=True)